let pyodide = null;
window.showToast = msg => { const t = document.getElementById("toast"); t.innerText = msg; t.classList.remove("hidden"); setTimeout(() => t.classList.add("hidden"), 2000); };
window.loadFeature = (html, cb) => { document.getElementById("main-content").innerHTML = html; if(cb) cb(); };

const tools = [
    { id: 'chat', name: 'AI Chat', emoji: '🧠', color: 'violet', load: () => loadFeature(`<div class="max-w-2xl mx-auto h-full flex flex-col"><h1 class="text-2xl font-semibold mb-4">🧠 AI Chat</h1><div id="chatBox" class="flex-1 bg-zinc-900 rounded-2xl p-4 overflow-y-auto flex flex-col gap-2 mb-4"></div><div class="flex gap-2"><input id="userInput" type="text" placeholder="Ask AI..." class="flex-1 bg-zinc-800 rounded-xl px-4 py-3"><button onclick="sendChatMessage()" class="px-6 bg-violet-600 rounded-xl font-semibold">Send</button></div></div>`, () => document.getElementById("chatBox").innerHTML = `<div class="ai-msg chat-message">Hello! Ami apnar AI Assistant.</div>`) },
    { id: 'globalchat', name: 'Global Chat', emoji: '🌍', color: 'emerald', load: () => loadFeature(`<div class="max-w-2xl mx-auto h-full flex flex-col"><h1 class="text-2xl font-semibold mb-4 text-emerald-400">🌍 Global Live Chat</h1><div id="globalChatBox" class="flex-1 bg-zinc-900 rounded-2xl p-4 overflow-y-auto flex flex-col gap-2 mb-4"></div><div class="flex gap-2"><input id="globalUserInput" type="text" placeholder="Type live message..." class="flex-1 bg-zinc-800 rounded-xl px-4 py-3" onkeypress="if(event.key==='Enter') sendGlobalChatMessage()"><button onclick="sendGlobalChatMessage()" class="px-6 bg-emerald-600 rounded-xl font-semibold">Send</button></div></div>`, () => window.startGlobalChatListener ? window.startGlobalChatListener() : null) },
    { id: 'image', name: 'Image Studio', emoji: '🎨', color: 'fuchsia', load: () => loadFeature(`<div class="max-w-xl mx-auto"><h1 class="text-2xl font-semibold mb-4">🎨 Image Generator</h1><div class="flex gap-2"><input id="imagePrompt" type="text" value="Futuristic city" class="flex-1 bg-zinc-800 rounded-xl px-4 py-3"><button onclick="generateImage()" class="px-6 bg-fuchsia-600 rounded-xl font-semibold">Generate</button></div><div id="imageResult" class="mt-6 min-h-[300px] bg-zinc-900 rounded-2xl flex items-center justify-center overflow-hidden border border-white/5"></div></div>`) },
    { id: 'python', name: 'Python Lab', emoji: '🐍', color: 'amber', load: () => loadFeature(`<div class="max-w-2xl mx-auto"><h1 class="text-2xl font-semibold mb-4">🐍 Python Lab</h1><textarea id="pythonCode" class="w-full h-48 bg-zinc-900 rounded-2xl p-4 font-mono text-sm">print("Hello NEXUS Python")</textarea><button onclick="runPythonCode()" class="mt-3 px-6 py-2 bg-emerald-600 rounded-xl">Run Code</button><pre id="pythonOutput" class="mt-4 w-full h-32 bg-black rounded-xl p-4 font-mono text-xs text-emerald-300 overflow-auto"></pre></div>`) },
    { id: 'terminal', name: 'Code Lab', emoji: '💻', color: 'cyan', load: () => loadFeature(`<div class="max-w-4xl mx-auto"><h1 class="text-2xl font-semibold mb-4">💻 Code Lab</h1><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><textarea id="codeInput" class="h-48 bg-zinc-900 rounded-2xl p-4 font-mono text-sm">&lt;h1 style="color:#10b981;text-align:center;"&gt;NEXUS Web&lt;/h1&gt;</textarea><iframe id="previewFrame" class="h-48 bg-white rounded-2xl w-full"></iframe></div><button onclick="runCode()" class="mt-3 px-6 py-2 bg-emerald-600 rounded-xl">Run HTML</button></div>`) },
    { id: 'weather', name: 'Live Weather', emoji: '⛅', color: 'sky', load: () => loadFeature(`<div class="max-w-md mx-auto"><h1 class="text-2xl font-semibold mb-4 text-sky-400">⛅ Live Weather</h1><div class="flex gap-2 mb-4"><input id="cityInput" type="text" placeholder="যেমন: Bardhaman" class="flex-1 bg-zinc-800 rounded-xl px-4 py-3" onkeypress="if(event.key==='Enter') getWeather()"><button onclick="getWeather()" class="px-6 bg-sky-600 rounded-xl font-semibold">Search</button></div><div id="weatherResult" class="bg-zinc-900 rounded-2xl p-6 text-center border border-white/5 hidden"></div></div>`) },
    { id: 'browser', name: 'Web Browser', emoji: '🌐', color: 'blue', load: () => loadFeature(`<div class="max-w-4xl mx-auto flex flex-col h-full min-h-[500px]"><div class="flex justify-between items-center mb-4"><h1 class="text-2xl font-semibold text-blue-400">🌐 Web Browser</h1><a id="extLink" href="#" target="_blank" class="hidden text-sm bg-blue-600 text-white px-4 py-2 rounded-xl flex items-center gap-2">Open in New Tab</a></div><div class="flex gap-2 mb-4"><input id="browserInput" type="text" placeholder="Search..." class="flex-1 bg-zinc-800 rounded-xl px-4 py-3" onkeypress="if(event.key==='Enter') loadBrowser()"><button onclick="loadBrowser()" class="px-6 bg-blue-600 rounded-xl font-semibold">Search</button></div><div id="browserWrapper" class="flex-1 w-full bg-white rounded-2xl overflow-hidden hidden border border-white/10"><iframe id="browserFrame" class="w-full h-full min-h-[500px] border-0"></iframe></div></div>`) },
    { id: 'library', name: 'Library', emoji: '📚', color: 'indigo', load: () => loadFeature(`<div class="max-w-4xl mx-auto flex flex-col h-full min-h-[600px]"><h1 class="text-2xl font-semibold mb-4 text-indigo-400">📚 Library & Wiki</h1><div class="flex gap-2 mb-4"><input id="libSearchInput" type="text" placeholder="Enter book or topic..." class="flex-1 bg-zinc-800 rounded-xl px-4 py-3 focus:outline-none" onkeypress="if(event.key==='Enter') searchAllAPIs()"><button onclick="searchAllAPIs()" class="px-6 bg-indigo-600 rounded-xl font-semibold transition active:scale-95">Search</button></div><div class="flex gap-2 mb-4 overflow-x-auto pb-2 scrollbar-hide"><button onclick="switchLibTab('googleTab', this)" class="lib-tab-btn active px-4 py-2 bg-indigo-600 text-white rounded-xl font-semibold whitespace-nowrap text-sm border border-transparent">Google Books</button><button onclick="switchLibTab('openlibTab', this)" class="lib-tab-btn px-4 py-2 bg-zinc-900 border border-white/10 text-zinc-400 rounded-xl font-semibold whitespace-nowrap text-sm">Open Library</button><button onclick="switchLibTab('wikiTab', this)" class="lib-tab-btn px-4 py-2 bg-zinc-900 border border-white/10 text-zinc-400 rounded-xl font-semibold whitespace-nowrap text-sm">Wikipedia</button></div><div id="googleTab" class="lib-content-area grid grid-cols-2 md:grid-cols-4 gap-4 overflow-y-auto pb-6"></div><div id="openlibTab" class="lib-content-area hidden grid grid-cols-2 md:grid-cols-4 gap-4 overflow-y-auto pb-6"></div><div id="wikiTab" class="lib-content-area hidden grid grid-cols-2 md:grid-cols-4 gap-4 overflow-y-auto pb-6"></div></div>`) },
    { id: 'mangadex', name: 'MangaDex', emoji: '⛩️', color: 'orange', load: () => loadFeature(`<div class="max-w-4xl mx-auto flex flex-col h-full min-h-[500px]"><h1 class="text-2xl font-semibold mb-4 text-orange-400">⛩️ Manga Search</h1><div class="flex gap-2 mb-4"><input id="mangaInput" type="text" placeholder="Search manga..." class="flex-1 bg-zinc-800 rounded-xl px-4 py-3" onkeypress="if(event.key==='Enter') searchManga()"><button onclick="searchManga()" class="px-6 bg-orange-600 rounded-xl font-semibold">Search</button></div><div id="mangaResults" class="grid grid-cols-2 md:grid-cols-4 gap-4 overflow-y-auto pb-6"><div class="col-span-2 md:col-span-4 text-center text-zinc-500 py-8">Search to see MangaDex results.</div></div></div>`) },
    { id: 'duckduckgo', name: 'DuckDuckGo', emoji: '🦆', color: 'yellow', load: () => loadFeature(`<div class="max-w-2xl mx-auto flex flex-col h-full min-h-[500px]"><h1 class="text-2xl font-semibold mb-4 text-yellow-400">🦆 DuckDuckGo</h1><div class="flex gap-2 mb-4"><input id="ddgInput" type="text" placeholder="Ask DuckDuckGo..." class="flex-1 bg-zinc-800 rounded-xl px-4 py-3" onkeypress="if(event.key==='Enter') searchDDG()"><button onclick="searchDDG()" class="px-6 bg-yellow-600 text-zinc-900 rounded-xl font-semibold">Search</button></div><div id="ddgResults" class="overflow-y-auto pb-6"></div></div>`) },
    { id: 'urlscan', name: 'URL Scanner', emoji: '📸', color: 'rose', load: () => loadFeature(`<div class="max-w-2xl mx-auto flex flex-col h-full min-h-[500px]"><h1 class="text-2xl font-semibold mb-4 text-rose-400">📸 URL Scanner & Screenshot</h1><div class="flex gap-2 mb-4"><input id="scanInput" type="text" placeholder="Enter website URL (e.g. google.com)..." class="flex-1 bg-zinc-800 rounded-xl px-4 py-3" onkeypress="if(event.key==='Enter') scanUrl()"><button onclick="scanUrl()" class="px-6 bg-rose-600 rounded-xl font-semibold">Scan</button></div><div id="scanResult" class="hidden overflow-y-auto pb-6 mt-4"></div></div>`) }
];

window.sendChatMessage = async () => { const input = document.getElementById("userInput"); const chatBox = document.getElementById("chatBox"); const text = input.value.trim(); if (!text) return; chatBox.innerHTML += `<div class="user-msg chat-message"><span class="text-sm">${text}</span></div>`; input.value = ""; const id = 'th-'+Date.now(); chatBox.innerHTML += `<div id="${id}" class="ai-msg chat-message">Thinking...</div>`; try { const res = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt: text }) }); const data = await res.json(); document.getElementById(id).remove(); chatBox.innerHTML += `<div class="ai-msg chat-message"><span class="text-sm">${data.reply || "No reply."}</span></div>`; } catch (e) { document.getElementById(id).innerText = "Error."; } chatBox.scrollTop = chatBox.scrollHeight; };
window.generateImage = () => { const prompt = encodeURIComponent(document.getElementById("imagePrompt").value.trim()); const url = `https://image.pollinations.ai/prompt/${prompt}?width=1024&height=1024&nologo=true&seed=${Date.now()}`; const div = document.getElementById("imageResult"); div.innerHTML = `<div class="animate-spin w-8 h-8 border-2 border-fuchsia-500 border-t-transparent rounded-full"></div>`; const img = new Image(); img.onload = () => div.innerHTML = `<img src="${url}" class="max-h-[350px] object-cover rounded-xl">`; img.src = url; };
window.runPythonCode = async () => { const output = document.getElementById("pythonOutput"); output.textContent = "Running...\n"; try { if (!pyodide) { window.showToast("Loading Python..."); pyodide = await loadPyodide(); } output.textContent += await pyodide.runPythonAsync(document.getElementById("pythonCode").value) || "Executed."; } catch (err) { output.textContent += "Error: " + err.message; } };
window.runCode = () => { const doc = document.getElementById("previewFrame").contentWindow.document; doc.open(); doc.write(document.getElementById("codeInput").value); doc.close(); };
window.getWeather = async () => { const city = document.getElementById("cityInput").value.trim() || "Bardhaman"; const div = document.getElementById("weatherResult"); div.classList.remove("hidden"); div.innerHTML = "Loading..."; try { const res = await fetch(`https://wttr.in/${encodeURIComponent(city)}?format=j1`); const data = await res.json(); const c = data.current_condition[0]; div.innerHTML = `<div class="text-5xl font-bold mb-3">${c.temp_C}°C</div><div class="text-xl">${c.weatherDesc[0].value}</div><div class="text-sm">Humidity: ${c.humidity}%</div>`; } catch(e) { div.innerHTML = "Error."; } };
window.loadBrowser = () => { const input = document.getElementById("browserInput").value.trim(); if (!input) return; document.getElementById("browserWrapper").classList.remove("hidden"); let url = input; if (!/^https?:\/\//i.test(url)) url = url.includes('.') ? 'https://'+url : `https://www.bing.com/search?q=${encodeURIComponent(input)}&igu=1`; document.getElementById("browserFrame").src = url; document.getElementById("extLink").href = url; document.getElementById("extLink").classList.remove("hidden"); };
window.switchLibTab = (tabId, el) => { document.querySelectorAll('.lib-tab-btn').forEach(btn => btn.className = 'lib-tab-btn px-4 py-2 bg-zinc-900 border border-white/10 text-zinc-400 rounded-xl font-semibold text-sm'); document.querySelectorAll('.lib-content-area').forEach(c => c.classList.add('hidden')); el.className = 'lib-tab-btn px-4 py-2 bg-indigo-600 text-white rounded-xl font-semibold text-sm active'; document.getElementById(tabId).classList.remove('hidden'); };

window.searchAllAPIs = () => { 
    const query = document.getElementById('libSearchInput').value.trim(); if (!query) return; 
    const load = '<div class="col-span-4 text-center py-8">Loading...</div>';
    ['googleTab', 'openlibTab', 'wikiTab'].forEach(id => document.getElementById(id).innerHTML = load);
    fetch(`https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(query)}&maxResults=8`).then(r=>r.json()).then(d => { document.getElementById('googleTab').innerHTML = d.items ? d.items.map(b => `<a href="${b.volumeInfo.infoLink}" target="_blank" class="bg-zinc-900 p-3 rounded-2xl"><img src="${b.volumeInfo.imageLinks?b.volumeInfo.imageLinks.thumbnail:''}" class="w-full h-36 object-cover rounded-xl mb-2"><div class="text-sm font-semibold">${b.volumeInfo.title}</div></a>`).join('') : 'No results'; });
    fetch(`https://openlibrary.org/search.json?q=${encodeURIComponent(query)}&limit=8`).then(r=>r.json()).then(d => { document.getElementById('openlibTab').innerHTML = d.docs ? d.docs.map(b => `<a href="https://openlibrary.org${b.key}" target="_blank" class="bg-zinc-900 p-3 rounded-2xl"><div class="text-sm font-semibold">${b.title}</div></a>`).join('') : 'No results'; });
    fetch(`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(query)}&utf8=&format=json&origin=*`).then(r=>r.json()).then(d => { document.getElementById('wikiTab').innerHTML = d.query.search ? d.query.search.map(w => `<a href="https://en.wikipedia.org/wiki/${encodeURIComponent(w.title)}" target="_blank" class="bg-zinc-900 p-3 rounded-2xl"><div class="text-sm font-semibold">${w.title}</div></a>`).join('') : 'No results'; });
};

window.searchManga = async () => {
    const query = document.getElementById('mangaInput').value.trim(); if(!query) return;
    const resDiv = document.getElementById('mangaResults'); resDiv.innerHTML = '<div class="col-span-2 md:col-span-4 text-center py-8">Searching Manga...</div>';
    try {
        const res = await fetch(`https://api.mangadex.org/manga?title=${encodeURIComponent(query)}&limit=8&includes[]=cover_art`);
        const data = await res.json();
        if(data.data && data.data.length > 0) {
            resDiv.innerHTML = data.data.map(m => {
                const title = m.attributes.title.en || Object.values(m.attributes.title)[0] || 'Unknown';
                const coverRel = m.relationships.find(r => r.type === 'cover_art');
                const coverFile = coverRel && coverRel.attributes ? coverRel.attributes.fileName : '';
                const imgUrl = coverFile ? `https://uploads.mangadex.org/covers/${m.id}/${coverFile}` : 'https://via.placeholder.com/150';
                return `<a href="https://mangadex.org/title/${m.id}" target="_blank" class="bg-zinc-900 border border-white/5 p-3 rounded-2xl flex flex-col hover:bg-zinc-800 transition"><img src="${imgUrl}" class="w-full h-36 object-cover rounded-xl mb-2 bg-zinc-800"><div class="text-sm font-semibold text-white line-clamp-2">${title}</div></a>`;
            }).join('');
        } else { resDiv.innerHTML = '<div class="col-span-2 md:col-span-4 text-center py-8">No manga found.</div>'; }
    } catch(e) { resDiv.innerHTML = '<div class="col-span-2 md:col-span-4 text-center py-8 text-red-400">Error fetching manga.</div>'; }
};

window.searchDDG = async () => {
    const query = document.getElementById('ddgInput').value.trim(); if(!query) return;
    const resDiv = document.getElementById('ddgResults'); resDiv.innerHTML = '<div class="text-center py-8">Searching...</div>';
    try {
        const res = await fetch(`https://api.duckduckgo.com/?q=${encodeURIComponent(query)}&format=json&no_html=1&skip_disambig=1`);
        const data = await res.json();
        if(data.AbstractText) {
            resDiv.innerHTML = `<div class="bg-zinc-900 p-4 rounded-xl border border-white/10"><h2 class="font-bold text-lg text-yellow-400 mb-2">${data.Heading}</h2><p class="text-zinc-300 text-sm mb-3">${data.AbstractText}</p><a href="${data.AbstractURL}" target="_blank" class="text-blue-400 text-sm underline">Read more</a></div>`;
        } else if (data.RelatedTopics && data.RelatedTopics.length > 0) {
            resDiv.innerHTML = data.RelatedTopics.filter(t => t.Text).slice(0,5).map(t => `<div class="bg-zinc-900 p-3 rounded-xl border border-white/10 mb-2"><a href="${t.FirstURL}" target="_blank" class="text-blue-400 text-sm underline block mb-1">${t.FirstURL}</a><p class="text-zinc-300 text-sm">${t.Text}</p></div>`).join('');
        } else {
            resDiv.innerHTML = `<div class="text-center py-8">No direct answer found. <br><a href="https://duckduckgo.com/?q=${encodeURIComponent(query)}" target="_blank" class="text-blue-400 underline mt-2 block">Search on DuckDuckGo</a></div>`;
        }
    } catch(e) { resDiv.innerHTML = '<div class="text-center py-8 text-red-400">Error connecting to DuckDuckGo.</div>'; }
};

window.scanUrl = () => {
    let url = document.getElementById('scanInput').value.trim(); if(!url) return;
    if(!/^https?:\/\//i.test(url)) url = 'https://' + url;
    const resDiv = document.getElementById('scanResult'); resDiv.classList.remove('hidden');
    resDiv.innerHTML = `<div class="animate-spin w-8 h-8 border-2 border-rose-500 border-t-transparent rounded-full mx-auto"></div><div class="text-center mt-2 text-sm text-zinc-400">Capturing Screenshot...</div>`;
    
    const imgUrl = `https://image.thum.io/get/width/1024/crop/800/${url}`;
    const img = new Image();
    img.onload = () => {
        resDiv.innerHTML = `<div class="bg-zinc-900 p-4 rounded-xl border border-white/10"><div class="flex items-center gap-2 mb-3 text-emerald-400"><i class="fa-solid fa-shield-check"></i> <span class="font-semibold text-sm">Scan Complete</span></div><a href="${url}" target="_blank" class="text-blue-400 text-xs mb-2 block truncate">${url}</a><img src="${imgUrl}" class="w-full rounded-lg border border-white/5 shadow-lg"></div>`;
    };
    img.onerror = () => { resDiv.innerHTML = `<div class="text-red-400 text-center py-4">Failed to capture screenshot. Make sure the URL is valid.</div>`; };
    img.src = imgUrl;
};

window.navigateTo = page => { if (page === 'home') { document.getElementById("main-content").innerHTML = `<div class="grid grid-cols-2 md:grid-cols-4 gap-4 mt-6" id="feature-grid"></div>`; document.getElementById("feature-grid").innerHTML = tools.map(t => `<div onclick="window.navigateTo('${t.id}')" class="glass-dark p-4 rounded-2xl cursor-pointer"><div class="text-3xl mb-2">${t.emoji}</div><div class="font-medium text-sm">${t.name}</div></div>`).join(''); } else { tools.find(t => t.id === page)?.load(); } };
window.handleLogin = () => { document.getElementById("login-screen").classList.add("hidden"); document.getElementById("dashboard-screen").classList.remove("hidden"); document.getElementById("sidebar").innerHTML = tools.map(t => `<div onclick="window.navigateTo('${t.id}')" class="px-3 py-2 text-sm cursor-pointer">${t.emoji} ${t.name}</div>`).join(''); window.navigateTo('home'); };
